server:
  port: 9003
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.200:8848 #配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'