server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #nacos服务注册中心地址
        server-addr: 192.168.100.200:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: 192.168.100.200:8858
        #默认8719端口，假如被占用自动从8719开始依次+1 扫描，直找到未被占用的端口
        prot: 8719
      datasource:
        #从nacos的配置信息中读取限流信息
        ds1:
          nacos:
            server-addr: 192.168.100.200:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

#监控图形化展现
management:
  endpoints:
    web:
      exposure:
        include: '*'
