server:
  port: 82
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.200:8848
#自定义：消费者将要访问的微服务名称（成功注册进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider